/* PART-6.2:---> */

/* b. MLOGIC: */
/* IT CAUSES THE MACRO PROCESSOR TO TRACE ITS EXECUTION AND TO WRITE THE TRACE INFORMATION TO THE SAS LOG. */
/* IF MLOGIC IS IN EFFECT AND THE MACRO PROCESSOR ENCOUNTERS A MACRO INVOCATION, 
		THE MACRO PROCESSOR DISPLAYS MESSAGES THAT IDENTIFY THE FOLLOWING:--> */
		
/* 		--> THE BEGINING OF MACRO EXECUTION. */
/* 		--> VALUES OF MACRO PARAMETERS AT INVOCATION. */
/* 		--> EXECUTION OF EACH MACRO PROGRAM STATEMENT. */
/* 		--> WHETHER EACH %IF CONDITION IS TRUE OR FALSE. */
/* 		--> THE ENDING OF MACRO EXECUTION. */


/* EG-1: */


OPTION MLOGIC;
%MACRO TESTING(TYPE);

%IF %UPCASE(&TYPE.) = SUV %THEN %DO;
PROC FREQ DATA=SASHELP.CARS;
TABLES ORIGIN;
RUN;
%END;

%IF %UPCASE(&TYPE.) = SPORTS %THEN %DO;
PROC FREQ DATA=SASHELP.CARS;
TABLES CYLINDERS;
RUN;
%END;


%ELSE %DO;
PROC FREQ DATA=SASHELP.CARS;
TABLES MAKE;
RUN;
%END;

%MEND;

%TESTING(SPORTS);






