/* PART-6.3:---> */

/* c. SYMBOLGEN: */
/* IT DISPLAY THE RESULTS OF RESOLVING MACRO VARIABLE REFERENCES. 
	THIS OPTION IS USEFUL FOR DUBUGGING. */

/* EG-1: */

OPTION SYMBOLGEN;
%MACRO CHECK_FRQ(TYPE, VAR);
PROC FREQ DATA=SASHELP.CARS;
TABLES &VAR.;
WHERE UPCASE(TYPE) = "&TYPE.";
RUN;
%MEND;

%CHECK_FRQ(SUV, ORIGIN);


/* NOTE:---> IF YOU ARE USING MACRO VARIABLE AS VALUE THEN ASIGN IT INTO DOUBLE QUOTES. */







