/* 1. DELETING BLANK OBSERVATIONS/ROWS:  */

/* IF ALL THE OBSEVATION IS BLANK THEN MISS_FLAG SHOW 1. */

DATA TEST;
SET WORK.car_mis;
MISS_FLAG = MISSING(CATS(of _all_));
IF MISS_FLAG = 1 THEN DELETE;
RUN; 

PROC PRINT DATA=TEST;
RUN;




/* 2. EXTRACTING N NUMBER OF CHARACTERS FROM RIGHT: */

/* RIGHT TO LEFT */

DATA TESTING;
SET WORK.ext;
LENGTHS= LENGTH(NAME);
LENGTHS2= LENGTH(EMAIL);
LENGTHS3= LENGTH(NAME)-4;

RIGHT_CHAR= SUBSTR(NAME,LENGTHS3,LENGTHS);
RIGHT_CHAR1= SUBSTR(NAME,LENGTH(NAME)-4,5);
RUN;

PROC PRINT DATA=TESTING;
RUN;





/* 3. DIFFERENCE BETWEEN TWO CONSECUTIVE ROW VALUES: */


DATA TEST1;
SET WORK.cons;
NEXT_AMOUNT = LAG(SALARY);
DIFF = SALARY-NEXT_AMOUNT;
RUN;

PROC PRINT DATA=TEST1;
RUN;





/* 4. REVERSE THE VALUE OF A VARIABLE:  */

DATA TEST2;
SET WORK.EXT(KEEP=NAME);
REVRS = REVERSE(NAME);
RUN;

PROC PRINT DATA = TEST2;
RUN;

/* WE ALSO REVERSE THE NUMERIC VALUE. AFTER CONVERTED, IT WILL BECOME CHARACTER VALUES. */





/* 5. EXPORT PROCEDURES' REPORTS INTO PDF OR EXCEL:  */

ODS PDF FILE = "/home/u63730693/my_sas/REPR.PDF";
PROC COMPARE BASE=WORK.TEST COMPARE=WORK.TEST1;
RUN;
ODS PDF CLOSE;





/* 6. ADDING LEADING ZEROS:  */

/* FIRST SEE WHICH OBSERVATION HAVING MAX LENGTH. */
/* Z--> IT IS FOR ADDING ZERO(0) */

DATA TEST4;
SET WORK.lzero;
ID2 = PUT(ID,Z7.);
RUN;





/* 7. EXPORT THE SAS LOGS IN A TEXT OR NOTEPAD FILE AUTOMATICALLY:  */


PROC PRINTTO LOG='/home/u63730693/my_sas/RES.LOG';
PROC COMPARE BASE=WORK.TEST COMPARE=WORK.TEST1;
RUN;

RUN;




/* 8. COUNT THE UNIQUE VALUES IN A VARIABLE:  */


PROC SQL;
SELECT COUNT(DISTINCT TEAM) AS TEAM_ALL
FROM SASHELP.BASEBALL;
QUIT;




/* 9. ARRANGE THE VARIABLE IN A REQUIRED SEQUENCE:  */

DATA TESTING1;
RETAIN TRA_DATE CARD_NUM NAME TRAN_AMOUNT;
SET WORK.TRANS;
RUN;

PROC PRINT DATA=TESTING1;





/* 10. HOW TO IMPORT A EXCEL FILE IN SAS ONDEMAND AND ALSO IN A USER-DEFINED LIBRARY:  */



/* HOW TO CREATE A USER-DEFINED LIBRARY OR PERMANENT LOCATION. */

LIBNAME TXT "/home/u63730693/my_sas";



/* IMPORT AN EXCEL FILES. */
/* IT IS STORE IN WORK LIBRARY. */
PROC IMPORT DATAFILE="/home/u63730693/my_sas/JOIN.xlsx"
				OUT=JOINN
				DBMS=xlsx REPLACE;
RUN;


/* TO STORE INTO A USER-DEFINED LIBRARY OR A PERMANENT LOCATION. */
PROC IMPORT DATAFILE="/home/u63730693/my_sas/JOIN.xlsx"
				OUT=TST.JOINN
				DBMS=xlsx REPLACE;
RUN;



