/* PROC SUMMARY: */

/* IT PRODUCES THE DESCRIPTIVE STATISTICAL SUMMARY FOR SUPPLIED DATA. */


/* EG-1: */
/* IT ONLY GIVE COUNT OF ROWS */
PROC SUMMARY DATA=SASHELP.CARS;
OUTPUT OUT =RESULT;
RUN; 

/* DIFF-1: */
/* PROC MEANS BY DEFAULT GIVE DESCRIPTIVE STATISTICAL SUMMARY BUT 
PROC SUMMARY BY DEFAULT GIVE COUNT OF ROWS THAT IS NOTHING BUT FREQUENCY OF ROW. */



/* EG-2: */
/* IT WILL GIVE A TABLE WITH SOME VARIABLES THAT IS:--> */
/* _TYPE_:--> IDENTIFY SPECIFIC COMBINATIONS OF CLASS VARIABLES TO USE TO SUBDIVIDE THE DATA. */
/* _FREQ_:--> NUMBER OF ROWS USED IN DESCRIPTIVE STATISTICS CALCULATION. */
/* _STAT_:--> NAME OF THE DESCRIPTIVE STATISTICS */
PROC SUMMARY DATA=SASHELP.CARS;
VAR HORSEPOWER;
OUTPUT OUT =RESULT;
RUN; 





/* EG-3: */
/* IT WILL GIVE THE RESULT BY GROUP. */
PROC SUMMARY DATA=SASHELP.CARS;
CLASS MAKE;
VAR HORSEPOWER;
OUTPUT OUT =RESULT;
RUN; 
PROC PRINT DATA=RESULT; RUN;



/* EG-4: */
/* IF YOU WANT SOME SPECIFIC STATISTICAL OPERATIONS. */
PROC SUMMARY DATA=SASHELP.CARS;
CLASS MAKE;
VAR HORSEPOWER;
OUTPUT OUT =RESULT MIN=MIN_HP MAX=MAX_HP SUM=TOTAL_HP;
RUN; 
PROC PRINT DATA=RESULT; RUN;




/* PROC MEANS VS PROC SUMMARY: */


/* DIFF-1: */
/* PROC MEANS BY DEFAULT GIVE DESCRIPTIVE STATISTICAL SUMMARY BUT 
PROC SUMMARY BY DEFAULT GIVE COUNT OF ROWS THAT IS NOTHING BUT FREQUENCY OF ROW. */

/* DIFF-2: */
PROC MEANS DATA=SASHELP.CARS;
RUN;

PROC SUMMARY DATA=SASHELP.CARS;
OUTPUT OUT=TESTS;
RUN;

/* PROC MEANS DIRECT PRINT THE RESULT. 
	BUT PROC SUMMARY ASK IN WHICH YOU STORE THE SUMMARY. */
	
/* IN PROC MEANS WE CAN STORE THE SUMMARY. */
PROC MEANS DATA=SASHELP.CARS;
OUTPUT OUT=TESTS1;
RUN;
/* WE CAN PRINT THE SUMMARY USING PROC SUMMARY */
PROC SUMMARY DATA=SASHELP.CARS PRINT;
OUTPUT OUT=TESTS;
RUN;
	
	





