/* PROC COMPARE IN SAS: */


/* PRAT-1:---> */

/* INTRODUCTION: */
/* IT COMPARES THE CONTENTS OF TWO SAS DATASETS, 
		SELECTED VARIABLES IN DIFFERENT DATASETS, 
		OR VARIABLES WITHIN THE SAME DATASET. */
		
/* WHAT IT COMAPRES? : */
/* a. NUMBER OF VARIABLES AND OBSERVATIONS IN BOTH OF THE DATASETS. */
/* b. VALUES IN THE MATCHING VARIABLES ARE SAME OR NOT. */
/* c. VARIABLES IN COMMON AND DIFFERENT IN DATASETS. */
/* d. ATTRIBUTES OF MATCHING VARIABLES. */

/* WHAT IS IT REQUIRED? : */
/* a. MIGRATION OF DATA FROM ONE DWH OR SYSTEM TO ANOTHER. */
/* b. CHANGES IN CODE */
/* c. REPORT VALIDATION */
/* d. DATA EDITING VALIDATION */



/* a. BASIC COMPARISION OF TWO DATA SETS: */

DATA CARR;
SET SASHELP.CARS;
RUN;

PROC PRINT DATA=CARR;


PROC COMPARE BASE= WORK.CARR1 COMPARE= WORK.CARR2;
				
RUN;




/* PART-2:--> */

/* b. COMPARISON WITH COMMON ID VARIABLE: */


/* FIRST SORT THE DATASET */

PROC SORT DATA=WORK.tt;
BY NAME;
RUN;

PROC SORT DATA=WORK.tt1;
BY NAME;
RUN;

/* THEN COMPARE THE DATASETS */

PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1;
ID NAME;
RUN;


/* PART-3:---> */

/* c. COMPARISON OF DATASET ATTRIBUTES OR METADATA: */


/* NOVALUES OPTION: */
PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1 NOVALUES;

RUN;


/* LISTVARS OPTION: */
PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1 LISTVARS;

RUN;



/* PART-4:--> */

/* d. COMPARISON OF DATASET BY OBSERVATIONS: */


/* FIRST SORT THE DATASET */

PROC SORT DATA=WORK.CARR1;
BY TYPE ORIGIN;
RUN;

PROC SORT DATA=WORK.CARR2;
BY TYPE ORIGIN;
RUN;

/* THEN COMPARE THE DATASETS */

PROC COMPARE BASE= WORK.CARR1 COMPARE= WORK.CARR2;
ID TYPE ORIGIN;
RUN;


/* LISTBASEOBS: */
/* IT GIVE DETAILS THOSE OBSERAVTION THAT EXISTS IN FIRST TABLE NOT IN EXISTS IN SECOND TABLE. */

PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1 LISTBASEOBS;

RUN;

/* LISTCOMPOBS: */
/* LIST THE OBSERAVTION FROM COMAPARE TABLE. */

PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1 LISTCOMPOBS;

RUN;

/* LISTOBS: */
/* THIS GIVE LIST OF ALL THE OBSERVATIONS */

PROC COMPARE BASE= WORK.TT COMPARE= WORK.TT1 LISTOBS;

RUN;


/* PART-5:---> */


/* e. COMPARISON OF VARIABLES IN THE SAME DATASET: */


PROC COMPARE BASE=SASHELP.PRDSALE MAXPRINT=20;
VAR ACTUAL;
WITH PREDICT;
RUN;














