/* PROC RANK OR RANK PROCEDURE:  */

/* THE RANK PROCEDURE COMPUTES RANKS FOR ONE OR MORE NUMERIC VARIABLES ACROSS THE OBSERVATIONS OF A SAS DATASET 
		AND WRITES THE RANKS TO A NEW SAS DATASET. 
		PROC RANK BY ITSELF PROCEDURES NO PRINTED OUTPUT. */

/* SYNTAX--> */
/* PROC RANK DATA=<INPUT TABLE> OUT<OUTPUT TABLE>; */
/* VAR<VARIABLE ON WHICH RANKING HAS TO BE DONE>; */
/* RANKS<NEW_VARIABLE_NAME>; */
/* RUN; */



DATA TESTING;
SET WORK.RNK;
RUN;

/* EG-1: */
/* MIN HEIGHT IS RANKED AS 1. */
PROC RANK DATA=WORK.RNK  OUT=TEST_RANK;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;


/* EG-2: */
/* MAX HEIGHT IS RANKED AS 1 */
PROC RANK DATA=WORK.RNK DESCENDING OUT=TEST_RANK;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;


/* EG-3: */
/* SAME HEIGHT IS RANKED SAME VALUE. */
/* IN THAT SCENARIO SAS USE MEAN RANKING--DEFAULT */
PROC RANK DATA=WORK.RNK DESCENDING OUT=TEST_RANK;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;

/* IF YOU WANT TO ASSIGN DIFFERENT RANK. */

/* IT WILL GIVE LOWEST VALUE  */
PROC RANK DATA=WORK.RNK DESCENDING OUT=TEST_RANK TIES=LOW;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;

/* IT WILL GIVE HIGHEST VALUE  */
PROC RANK DATA=WORK.RNK DESCENDING OUT=TEST_RANK TIES=HIGH;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;

/* IT WILL GIVE LOWESR VALUE AND THE NEXT VALUE IT SUM IT WITH 1. */
PROC RANK DATA=WORK.RNK DESCENDING OUT=TEST_RANK TIES=DENSE;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
RUN;


/* RANKING WITH GROUPING: */
/* GROUP USING GENDER. */


PROC SORT DATA=TESTING;  BY GENDER; RUN;

PROC RANK DATA=TESTING  OUT=TEST_RANK;
VAR HEIGHT;
RANKS HEIGHT_RANKED;
BY GENDER;
RUN;

PROC PRINT DATA=TEST_RANK;
RUN;











