/* PROC SURVEY SELECT: */


PROC PRINT DATA=SASHELP.CARS; RUN;

/* a. SIMPLE EXAMPLE: */
/* SCENARIO-1: */
/* IT WILL SHOW ONLY 10 RECORDS WITH ALL COLUMNS. */
/* SRS--> SIMPLE RANDOM SAMPLING */
PROC SURVEYSELECT DATA=SASHELP.CARS OUT=SR_CARS METHOD=SRS SAMPSIZE=10;
RUN;
PROC PRINT DATA=SR_CARS; RUN;

/* SCENARIO-2: */
/* IT WILL SHOW ONLY 10% RECORDS WITH ALL COLUMNS. */
PROC SURVEYSELECT DATA=SASHELP.CARS OUT=SR_CARS METHOD=SRS RATE=.10;
RUN;
PROC PRINT DATA=SR_CARS; RUN;


/* SCENARIO-3: */
/* IT WILL SHOW ONLY 10% RECORDS WITH SOME SPECIFIC COLUMNS. */
PROC SURVEYSELECT DATA=SASHELP.CARS OUT=SR_CARS METHOD=SRS RATE=.10;
ID MAKE TYPE MODEL ORIGIN;
RUN;
PROC PRINT DATA=SR_CARS; RUN;




/* SCENARIO-3: */
/*  STRATA SAMPLING:  */
/* IT WILL SHOW ONLY 10% RECORDS WITH SOME SPECIFIC COLUMNS. */
PROC SORT DATA=SASHELP.CARS OUT=CARSS; BY DRIVETRAIN; RUN;
PROC SURVEYSELECT DATA=CARSS OUT=SR_CARS METHOD=SRS SAMPSIZE=2;
ID MAKE TYPE MODEL ORIGIN DRIVETRAIN;
STRATA DRIVETRAIN;
RUN;
PROC PRINT DATA=SR_CARS; RUN;












