/* PROC TABULATE: */

/* IT IS THE PROCEDURE WHICH HELPS TO PRESENT DESCRIPTIVE STATISTICS IN A TABULAR FORMAT PROFESSIONALLY. */

/* SYNTAX--> */
/* PROC TABULATE DATA=<TABLE_NAME>; */
/* CLASS<VARIABLES>;    CATEGORY VARIABLES FOR CREATING CATEGORIZATION */
/* VAR<VARIABLES>;      NUMERIC VARIABLE FOR MATHEMATIC OPERATION */
/* TABLES<VARIABLES>;   MATHEMATICAL OPERATIONS LIKE 'SUM,MEAN,DIVISON' */
/* RUN; */


/* NOTE:--> */
/* TABLES ,  ;-->  */
/* IN THE RIGHT HAND SIDE OF COMMA YOU PUT VARIABLE WHICH YOU SEE IN THE COLUMN LABEL */
/* IN THE LEFT HAND SIDE OF COMMA YOU PUT VARIABLE WHICH YOU SEE IN THE ROW LABEL */

/* TABLES VAR1*VAR2;--> */
/* IT WILL TAKE EVREYTHING INTO COLUMN LABEL. */



/* EG-1: */
/* TABLES ,  ;-->  */
/* IN THE RIGHT HAND SIDE OF COMMA YOU PUT VARIABLE WHICH YOU SEE IN THE COLUMN LABEL */
/* IN THE LEFT HAND SIDE OF COMMA YOU PUT VARIABLE WHICH YOU SEE IN THE ROW LABEL */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
TABLES ORIGIN,TYPE;
RUN;


/* EG-2: */
/* TABLES VAR1*VAR2;--> */
/* IT WILL TAKE EVREYTHING INTO COLUMN LABEL. */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
TABLES ORIGIN*TYPE;
RUN;


/* EG-3: */
/* IF YOU SEE THE GRAND_TOTAL IN ROW LABEL. */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
TABLES ORIGIN ALL="GRAND_TOTAL",TYPE;
RUN;


/* EG-4: */
/* IF YOU SEE THE GRAND_TOTAL IN COLUMN LABEL. */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
TABLES ORIGIN ,TYPE ALL="GRAND_TOTAL";
RUN;


/* EG-5: */
/* IF YOU SEE THE GRAND_TOTAL IN BOTH COLUMN AND ROW LABEL. */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
TABLES ORIGIN ALL="GRAND_TOTAL" ,TYPE ALL="GRAND_TOTAL";
RUN;


/* EG-6: */
/* ORIGIN WISE TYPE WISE SUM OF MSRP. */
/* BY DEFAULT IT WILL SHOW SUM */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
VAR MSRP;
TABLES TYPE,ORIGIN*MSRP;
RUN;


/* EG-7: */
/* ORIGIN WISE TYPE WISE AVG OF MSRP. */

PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE;
VAR MSRP;
TABLES TYPE,ORIGIN*MSRP*(N SUM MEAN);
RUN;


/* EG-8: */
/* MULTIPLE VARIABLE SUMMARY. */

/* SCENARIO-1: */
PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE DRIVETRAIN;
VAR MSRP;
TABLES ORIGIN*TYPE,DRIVETRAIN*MSRP*(N SUM MEAN);
RUN;


/* SCENARIO-2: */
/* IT WILL CRAETE A SEPARATE TABLE FOR INVOICE */
PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE DRIVETRAIN;
VAR MSRP INVOICE;
TABLES ORIGIN*TYPE,DRIVETRAIN*MSRP INVOICE*(N SUM MEAN);
RUN;

/* SCENARIO-3: */
PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE DRIVETRAIN;
VAR MSRP INVOICE;
TABLES ORIGIN*TYPE,DRIVETRAIN*(MSRP INVOICE)*(N SUM MEAN);
RUN;


/* SCENARIO-3: */
/* IF YOU WANT TO SUM FOR MSRP AND AVG FOR INVOICE */
PROC TABULATE DATA=SASHELP.CARS;
CLASS ORIGIN TYPE DRIVETRAIN;
VAR MSRP INVOICE;
TABLES ORIGIN*TYPE,DRIVETRAIN*MSRP*(SUM="TOTAL") 
					DRIVETRAIN*INVOICE*(N="COUNT" MEAN="AVG");
RUN;









