/* DATA TYPE CONVERSION: */      (/* INPUT AND PUT FUNCTION: */)

/* DATA IMPORTING */

PROC IMPORT DATAFILE='/home/u63730693/my_sas/CHART.xlsx'
				OUT=ACCOUNT_CUST
				DBMS=xlsx replace;
				SHEET='sheet2';
RUN;

/* DATA READING */

DATA TEST;
SET WORK.account_cust;
RUN;



/* a. PUT FUNCTION: */

/* IT CONVERTS THE DATA FROM NUMERIC TO CHARACTER. */

/* SYNTAX--> PUT(SOURCE, FORMAT.) */

/* FORMAT. : IN WHICH YOU WANT TO DISPLAY THE DATA. */

/* EG-1: */
/* CONVERT "ACCOUNT_NUMBER" TO CHARACTER. */

DATA TEST;
SET WORK.account_cust;
acc_num=COMPRESS(PUT(ACCOUNT_NUMBER,BEST.));
RUN;



/* b. INPUT FUNCTION: */

/* IT CONVERTS THE DATA FROM CHARACTER TO NUMERIC. */

/* SYNTAX--> INPUT(SOURCE, INFORMAT.) */

/* INFORMAT. : THE FORMAT IN WHICH THE DATA ALREADY EXITS. */


/* EG-2: */
/* CONVERT THE CHARACTER TO NUMERIC */

DATA TEST;
SET WORK.account_cust;
acc_num=COMPRESS(PUT(ACCOUNT_NUMBER,BEST.));
ACC_numm=INPUT(acc_num,12.);
RUN;