/* 1. DELETING A DATASET OR DATASETS FROM A LIBRARY OR LIBRARIES:  */

LIBNAME HOME '/home/u63730693/my_sas';

/* CREATE SOME DATASETS. */
DATA A1; Z=1; RUN;
DATA A2; Z=2; RUN;
DATA A3; Z=3; RUN;
DATA A4; Z=4; RUN;
DATA A5; Z=5; RUN;
DATA A6; Z=6; RUN;
DATA A7; Z=7; RUN;
DATA B1; Z=8; RUN;
DATA B2; Z=9; RUN;
DATA B3; Z=10; RUN;
DATA B4; Z=11; RUN;
DATA B5; Z=12; RUN;
DATA HOME.B1; Z=8; RUN;
DATA HOME.B2; Z=9; RUN;
DATA HOME.B3; Z=10; RUN;
DATA HOME.B4; Z=11; RUN;
DATA HOME.B5; Z=12; RUN;

/* DELETE ALL THE DATASETS FROM ONE LIBRARY: */
PROC DATASETS LIB=WORK KILL; RUN;

/* IT WILL SHOW ALL THE DATASETS WITH NAME AND SOME INFORMATIONS */
PROC DATASETS LIB=WORK MEMTYPE=DATA;
RUN;

/* DELETE ALL DATASETS EXCEPT SOME DATASETS: */
PROC DATASETS LIB=WORK NOLIST; 
	SAVE A5 A7;
RUN;

/* DELETE ALL DATASETS EXCEPT THE DATASET START WITH 'A': */
PROC DATASETS LIB=WORK NOLIST; 
	SAVE A:;
RUN;

/* DELETE ALL DATASETS EXCEPT THE DATASET IN A RANGE: */
PROC DATASETS LIB=WORK NOLIST; 
	SAVE A1-A5;
RUN;

/* DELETE SPECIFIC DATASETS: */
PROC DATASETS LIB=WORK NOLIST; 
	DELETE A1-A5;
RUN;

/* DELETE TABLES THAT START WITH "B": */
PROC DATASETS LIB=WORK NOLIST; 
	DELETE B:;
RUN;

/* DELETE DATASETS FROM DIFFERENT LIBRARIES: */
PROC DELETE DATA=WORK.A7 HOME.B1; 	
RUN;

