/* PROC UNIVARIATE: */

/* IT IS USED TO CHECK THE DATA DISTRIBUTION, 
	GET DESCRIPTIVE STATISTICS, 
	DO THE NORMALITY ASSESSMENT AND 
	DISCOVERY OF OUTLIERS, 
	HYPOTHESIS TESTING AND MANY MORE. */
	
DATA CAR_SUBSET;
SET SASHELP.CARS;
KEEP ORIGIN MSRP INVOICE;
RUN;

PROC PRINT DATA=CAR_SUBSET;
RUN;



/* EG-1: */

/* IT WILL SHOW THE STATISTICAL SUMMARY FOR ALL NUMERIC VARIABLES. */
PROC UNIVARIATE DATA=CAR_SUBSET;
RUN;



/* EG-2: */

/* IT WILL SHOW THE STATISTICAL SUMMARY FOR ONLY ONE NUMERIC VARIABLE. */
PROC UNIVARIATE DATA=CAR_SUBSET;
VAR MSRP;
RUN;


/* EG-3: */

/* IT WILL SHOW THE STATISTICAL SUMMARY FOR ONLY ONE NUMERIC VARIABLE GROUP BY CATEGORY (ORIGIN VARIABLE). */
PROC UNIVARIATE DATA=CAR_SUBSET;
VAR MSRP;
CLASS ORIGIN;
RUN;


/* EG-4: */

/* IT WILL SHOW BASIC MEASURES ONLY */
ODS SELECT BASICMEASURES;
PROC UNIVARIATE DATA=CAR_SUBSET;
VAR MSRP;
RUN;



/* EG-5: */

/* IT WILL GIVE THE TITLE. */
ODS SELECT BASICMEASURES;
PROC UNIVARIATE DATA=CAR_SUBSET;
TITLE BASIC MEASURES;
VAR MSRP;
RUN;



/* EG-6: */

/* IT WILL GIVE THE FOOTNOTE. */
ODS SELECT BASICMEASURES;
PROC UNIVARIATE DATA=CAR_SUBSET;
TITLE BASIC MEASURES;
VAR MSRP;
FOOTNOTE "THIS IS THE END";
RUN;


/* EG-7: */

/* IT WILL CREATE A HISTOGRAM PLOT WITH SUMMARY REPORT. */
ODS SELECT ExtremeObs;
PROC UNIVARIATE DATA=CAR_SUBSET;
TITLE "BASIC MEASURES";
VAR MSRP;
HISTOGRAM;
FOOTNOTE "THIS IS THE END";
RUN;




PROC UNIVARIATE DATA=CAR_SUBSET PLOTS;
VAR MSRP;
RUN;




